### PR TITLE
Fix error in Italian TM and add links for TeachOSM and OSMUS TM at version 4

### PR DESCRIPTION
**Pull request by LorenzoStucchi**
@regazzoj I found an error in the use of the tool with the Italian Tasking Manager, so I fix the code.
I also check the other TM and fox the link for the TeachOSM and the OSMUS that are now at version 4 of the TM.

### CODE REVIEW

**Comment by regazzoj** [comment]
Thank you (:

**Comment by LorenzoStucchi** [comment]
Hi, there are again some issue and it is not working with version 4 of the other TM.
For the Italian TM:
`abbreviatedOptions: "?abbreviated=true",`
should be corrected with
`abbreviatedOptions: "/?abbreviated=true",`

However, there are other errors and the tool doesn't work with the TM at version 4 outside HOT

**Comment by regazzoj** [comment]
Tell me if my last commits fix it (:

**Comment by LorenzoStucchi** [comment]
Thanks @regazzoj , I check and no more errors are shown. However, if I try to show some results of the marathon nothing is shown for the Italian TM.
I try with the project [76](https://osmit-tm4.wmcloud.org/projects/76), it is possible to check that some [mapping](https://osmcha.org/changesets/99066693?filters=%7B%22in_bbox%22%3A%5B%7B%22label%22%3A%227.8834321%2C44.5189941%2C8.513625%2C45.1330048%22%2C%22value%22%3A%227.8834321%2C44.5189941%2C8.513625%2C45.1330048%22%7D%5D%2C%22area_lt%22%3A%5B%7B%22label%22%3A2%2C%22value%22%3A2%7D%5D%2C%22date__gte%22%3A%5B%7B%22label%22%3A%222021-01-19%22%2C%22value%22%3A%222021-01-19%22%7D%5D%2C%22comment%22%3A%5B%7B%22label%22%3A%22%23osmitaly-76%20%23improveasti%22%2C%22value%22%3A%22%23osmitaly-76%20%23improveasti%22%7D%5D%7D) has been done in the last 24h, but in the tool I don't have results.

Example

**Comment by regazzoj** [comment]
@LorenzoStucchi Just to let you know that I have found an issue and I will fix it asap.

**Comment by regazzoj** [comment]
@LorenzoStucchi I fix the issue for OSM Italy. I still need to fix some TM.
The fix is online, if you want to test it.

**Pull request merged**
