### PR TITLE
feat: add MapWithAI to list of available Tasking Managers

### PR DESCRIPTION
**Pull request by cbeddow**
I have added in the MapWithAI Tasking Manager from Meta to the list of available TMs to choose from. This will be very helpful for multiple Youthmappers communities and other partners who are mapping pedestrian infrastructure using MapWithAI TM and Rapid 2.1 editor.

### CODE REVIEW

**Comment by cbeddow** [comment]
@LorenzoStucchi do you know who is the best person to review and accept this?

**Comment by LorenzoStucchi** [comment]
Hi @cbeddow, last year, my PR was approved by @regazzoj. Or maybe @ViolaineDo could help you

**Comment by regazzoj** [comment]
Hey @cbeddow , thanks for your PR.
Can't test your change right now.
Does it work well and doesn't break other TM ?

**Comment by cbeddow** [comment]
@regazzoj let me double check on breaking and write back

**Comment by cbeddow** [comment]
Yes, looks good. Right now a lot of the work with MapWithAI is adding footways (sidewalks, crossings) so I am thinking of a second changeset to allow fetching that data. But this one works! The Overpass query tends to be slow, but that looks like it's not due to this dashboard.

**Comment by regazzoj** [comment]
Yeah... I may have a look to see if I can do anything for slow Overpass queries next week.
I will try to add footway changesets in the dashboard by next week.

Thanks for your commit !

**Pull request merged**
